apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: galaga-application-set
  namespace: fleet-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: red-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: galaga-{{name}}
    spec:
      project: red-team
      source:
        repoURL: https://github.com/rokej/RedApplications.git
        targetRevision: main
        path: galaga
      destination:
        namespace: galaga
        name: "argocd-agent-{{name}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
