apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: fleet-argocd-principal
  namespace: acm-gitops-policy
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-1 Data-at-rest
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: fleet-argocd-principal
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: fleet-gitops
            - complianceType: musthave
              objectDefinition:
                apiVersion: argoproj.io/v1beta1
                kind: ArgoCD
                metadata:
                  name: fleet-argocd
                  namespace: fleet-gitops
                spec:
                  controller:
                    enabled: false
                  argoCDAgent:
                    principal:
                      enabled: true
                      logLevel: "info"
                      auth: "mtls:CN=([^,]+)"
                      tls:
                        insecureGenerate: false
                  sourceNamespaces:
                    - "argocd-agent-blue-cluster"
                    - "argocd-agent-red-cluster"
                  applicationSet: {}
                  sso:
                    provider: dex
                    dex:
                      openShiftOAuth: true
                  server:
                    route:
                      enabled: true
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: fleet-argocd-principal
  namespace: acm-gitops-policy
placementRef:
  name: acm-hub-cluster
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: fleet-argocd-principal
    kind: Policy
    apiGroup: policy.open-cluster-management.io
